# Python 
Michigan University (CURSERA)

## 1. Numpy

In [2]:
import numpy as np
import math

## 1.1. Vectores y matrices

Numpy le da una capa lógica de matemáticas a las colecciones dentro de python, que por definición no la tiene. La únidad vásica es el "array" (arreglo); estos arrays pueden ser vectores (cuando solo una lista los compone), o matrices cuando estan compuestos por más de una lista. En este sentido, las listas dentro de un array puden ser interpretadas como vectores o **variables**.

In [5]:
# Crear un VECTOR:
vector = np.array([1,2,3,4,5])
print(vector)

# Crear una MATRIZ (con doble [[]])
matrix = np.array([
    # Variable 1
    [1,2,3],
    # Variable 2
    [4,5,6]
    ])
print(matrix)

# Tipo
print(type(matrix))

# ".ndim" el número de dimensiones (variables) del array
print("Variables vector: "+ str(vector.ndim))
print("Variables matriz: "+ str(matrix.ndim))

# ".shape" devuleve las dimensiones del array
print("Dimensiones vector: "+ str(vector.shape))
print("Dimensiones matriz: "+ str(matrix.shape))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Variables vector: 1
Variables matriz: 2
Dimensiones vector: (5,)
Dimensiones matriz: (2, 3)


## 1.2. Operaciones básicas

Antes,es importante anotar que el tipo de dato del array es homogeneo en todos sus elemenos: Es decir, si un valor del array es un string, y todos los demas son numeros enteros, entonces el array entero será un conjutno de strings. Siempre se generaliza hacia el tipo de dato más general, lo que se denomina "*upcasting*".

El comportamiento del los arrayes es "exatamente igual" que el de las matrices matemáticas: todo tiene que estar entonces correctametne específicado y dimensionado.

In [11]:
print("Matris original: ")
matrix = np.array([
    # Variable 1
    [1,2,3,4],
    # Variable 2
    [5,6,7,8]
    ])

print(matrix)

# Transponer la matriz
print("\nMatirz transpuesta:")
print(matrix.transpose())

#


Matris original: 
[[1 2 3 4]
 [5 6 7 8]]

Matirz transpuesta:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
