# Python 
Michigan University (CURSERA)

## 1. Numpy

In [13]:
import numpy as np
import re

### 1.1. Vectores y matrices

Numpy le da una capa lógica de matemáticas a las colecciones dentro de python, que por definición no la tiene. La únidad vásica es el "array" (arreglo); estos arrays pueden ser vectores (cuando solo una lista los compone), o matrices cuando estan compuestos por más de una lista. En este sentido, las listas dentro de un array puden ser interpretadas como vectores o **variables**.

In [5]:
# Crear un VECTOR:
vector = np.array([1,2,3,4,5])
print(vector)

# Crear una MATRIZ (con doble [[]])
matrix = np.array([
    # Variable 1
    [1,2,3],
    # Variable 2
    [4,5,6]
    ])
print(matrix)

# Tipo
print(type(matrix))

# ".ndim" el número de dimensiones (variables) del array
print("Variables vector: "+ str(vector.ndim))
print("Variables matriz: "+ str(matrix.ndim))

# ".shape" devuleve las dimensiones del array
print("Dimensiones vector: "+ str(vector.shape))
print("Dimensiones matriz: "+ str(matrix.shape))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
Variables vector: 1
Variables matriz: 2
Dimensiones vector: (5,)
Dimensiones matriz: (2, 3)


### 1.2. Operaciones básicas

Antes,es importante anotar que el tipo de dato del array es homogeneo en todos sus elemenos: Es decir, si un valor del array es un string, y todos los demas son numeros enteros, entonces el array entero será un conjutno de strings. Siempre se generaliza hacia el tipo de dato más general, lo que se denomina "*upcasting*".

El comportamiento del los arrayes es "exatamente igual" que el de las matrices matemáticas: todo tiene que estar entonces correctametne específicado y dimensionado.

In [14]:
print("Matris original: ")
matrix = np.array([
    # Variable 1
    [1,2,3,4],
    # Variable 2
    [5,6,7,8]
    ])

print(matrix)

# Transponer la matriz
print("\nMatirz transpuesta:")
print(matrix.transpose())

# Matriz buleana
print("\nMatriz bolleana (Números pares):")
print(matrix %2 ==0)

print("\nMatriz bolleana (x >5):")
print(matrix >5)


Matris original: 
[[1 2 3 4]
 [5 6 7 8]]

Matirz transpuesta:
[[1 5]
 [2 6]
 [3 7]
 [4 8]]

Matriz bolleana (Números pares):
[[False  True False  True]
 [False  True False  True]]

Matriz bolleana (x >5):
[[False False False False]
 [False  True  True  True]]


Al igual que en **R**, se pueden craar vectores alatorios, y redimensionarlos como matrices:


In [37]:
print("Creando vectores: ")
# Crear una secuencia (10 primeros multiplos de "pi")
print(np.arange(np.pi,np.pi*10,np.pi)) 

# Crear una lista con un número predetermnado de elementos
print(np.linspace(0,1,21))

# Redimensionar
print("\nRedimensionamineto de vectores: ")
print("\nVector inicial:")
print(np.arange(1,11,1))

print("\nMatriz Final:")
print(np.array(np.arange(1,11,1)).reshape((2,5)))

Creando vectores: 
[ 3.14159265  6.28318531  9.42477796 12.56637061 15.70796327 18.84955592
 21.99114858 25.13274123 28.27433388]
[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95 1.  ]

Redimensionamineto de vectores: 

Vector inicial:
[ 1  2  3  4  5  6  7  8  9 10]

Matriz Final:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 1.3. Slicing

El slicing en los arrays funciona similar a en R


In [42]:
data = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])
print("Matriz original:")
print(data)

print("\nExtraer primer vector")
print(data[0])

print("\nExtraer  ultimo elemtno de segundo vector")
print(data[1,-1])

print("\nPrimer valor de cada vector")
print(data[:,0])

Matriz original:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Extraer primer vector
[1 2 3 4 5]

Extraer  ultimo elemtno de segundo vector
10

Primer valor de cada vector
[1 6]


### 1.4. REGEX (algunas notas)


- `^` Inicio del string
- `$` Final del string
- `[]` Se denomina un "*set operator*": Todo lo que este dentro se maneja de manera indiviual `[ab]` busca todas las "a" o todas las "b" 
- `[^]` Niega lo que este dentro del set opertor
- `\w` Culaquier digito o letra


In [41]:
texto = "Hola como has estado, _ te he marcado como 100 veces. Donde andas?"
print("re.finall(...)")
print("\nab")
print(re.findall("ab", texto))

print("\n[ab]")
print(re.findall("[la]", texto))



re.finall(...)

ab
[]

[ab]
['l', 'a', 'a', 'a', 'a', 'a', 'a', 'a']


## 2. Pandas

In [42]:
import pandas as pd

In [47]:
data = ["guibor","tatiana","hael","None"]
pd.Series(data)

0     guibor
1    tatiana
2       hael
3       None
dtype: object

In [48]:
data = [1,None, 2,4]
pd.Series(data)

0    1.0
1    NaN
2    2.0
3    4.0
dtype: float64